#!/usr/bin/env python3
"""Generate skin token CSS from the canonical style guide.

Generated, never hand-edited. CI runs this script then `git diff --exit-code`.

`references/style-guide.md` stays the single source of truth for token values. This script
reads the role tables out of it and emits one `:root` block per variant, which templates and
examples inline verbatim. Reskinning is therefore a single block swap.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STYLE_GUIDE = REPO / "skills/diagram-design/references/style-guide.md"
OUT_DIR = REPO / "skills/diagram-design/assets/skins"

# The token contract. Every role here must be emitted or the build fails.
CONTRACT = (
    "paper", "paper-2", "node-white", "ink", "muted", "soft", "rule", "rule-solid",
    "accent", "accent-tint", "link",
    "series-1", "series-2", "series-3", "series-4", "series-5",
    "wash-2", "wash-3", "wash-5", "wash-10", "wash-20", "wash-30",
    "radius-node", "radius-tag", "radius-container",
)

VARIANTS = ("light", "dark")

# Geometry roles are written as bare numbers in the style guide, matching the SVG `rx`
# attribute's user units. The CSS `rx` geometry property needs a real length, so the
# generator emits them with an explicit unit — in SVG user space `1px` is one user unit,
# so `rx: 6px` and `rx="6"` are the same corner.
LENGTH_ROLES = frozenset({"radius-node", "radius-tag", "radius-container"})

ROLE_RE = re.compile(r"^\|\s*`([a-z0-9-]+)`\s*\|(.+)$")
HEADER_RE = re.compile(r"^\|\s*Role\s*\|", re.IGNORECASE)
CODE_SPAN_RE = re.compile(r"`([^`]+)`")


def cell_value(cell: str) -> str:
    """Return the token value from a table cell.

    Values are always written as a code span, optionally followed by a prose annotation —
    ``` `#7c8f6f` (sage) ``` yields ``#7c8f6f``. Falling back to the bare cell keeps the
    parser working if an annotation-free value is ever written without backticks.
    """
    match = CODE_SPAN_RE.search(cell)
    return (match.group(1) if match else cell).strip()


def read_roles() -> dict[str, dict[str, str]]:
    """Return {role: {"light": value, "dark": value}} for every contract role."""
    markdown = STYLE_GUIDE.read_text(encoding="utf-8")
    roles: dict[str, dict[str, str]] = {}
    headers: list[str] = []

    for line in markdown.splitlines():
        if HEADER_RE.match(line):
            headers = [cell.strip().casefold() for cell in line.strip().strip("|").split("|")]
            continue
        match = ROLE_RE.match(line)
        if not match:
            continue
        role = match.group(1)
        if role not in CONTRACT:
            continue
        if not headers:
            raise SystemExit(f"role {role!r} appears before any '| Role |' table header")
        cells = [cell_value(cell) for cell in match.group(2).split("|")]
        light = dark = ""
        for index, header in enumerate(headers[1:]):
            if index >= len(cells):
                break
            if "light" in header or header in {"default", "value"}:
                light = cells[index]
            elif "dark" in header:
                dark = cells[index]
        # A single-value table (geometry) uses the same value in both variants.
        roles[role] = {"light": light, "dark": dark or light}
    return roles


def render_skin(roles: dict[str, dict[str, str]], variant: str = "light") -> str:
    missing = [role for role in CONTRACT if role not in roles or not roles[role].get(variant)]
    if missing:
        raise SystemExit(f"style guide is missing contract roles: {', '.join(missing)}")
    lines = [
        "/* GENERATED by scripts/build-skins.py — do not edit by hand. */",
        f"/* variant: {variant} */",
        ":root {",
    ]
    for role in CONTRACT:
        value = roles[role][variant]
        if role in LENGTH_ROLES and re.fullmatch(r"\d+(?:\.\d+)?", value):
            value += "px"
        lines.append(f"  --dd-{role}: {value};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    roles = read_roles()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for variant in VARIANTS:
        target = OUT_DIR / f"active-{variant}.tokens.css"
        target.write_text(render_skin(roles, variant), encoding="utf-8")
        print(f"  {target.relative_to(REPO)}", file=sys.stderr)
    print(f"Done. {len(CONTRACT)} roles per variant.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
